os: linux
dist: bionic
language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - nightly

jobs:
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

install: composer install

script:
  - '[[ ${TRAVIS_PHP_VERSION:0:1} == "7" ]] && vendor/bin/php-cs-fixer fix --diff --dry-run || echo "Skipping coding standards check"'
  - vendor/bin/psalm --show-info=true
  - vendor/bin/phpunit --coverage-text
