#!/usr/bin/env php
<?php

use DI\ContainerBuilder;
use PHLAK\SemVerCLI\Bootstrap\AppManager;

for ($level = 0; $level <= 4; $level++) {
    $path = $level === 0 ? __DIR__ : dirname(__DIR__, $level);

    if (is_readable($autoloader = $path . '/vendor/autoload.php')) {
        require $autoloader;
        break;
    }
}

// Initialize the container
$container = (new ContainerBuilder)->addDefinitions(
    ...glob(__DIR__ . '/config/*.php')
)->build();

// Initialize the application
$app = $container->call(AppManager::class);

// Engage!
$app->run();
