#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use SemVerCli\Commands;
use Symfony\Component\Console\Application;

$app = new Application('Semantic versioning helper', '0.1.0');

$app->addCommands([
    // Initialize
    new Commands\Initialize,

    // Set
    new Commands\Set\Version,
    new Commands\Set\Major,
    new Commands\Set\Minor,
    new Commands\Set\Patch,
    new Commands\Set\PreRelease,
    new Commands\Set\Build,

    // Get
    new Commands\Get\Version,
    new Commands\Get\Major,
    new Commands\Get\Minor,
    new Commands\Get\Patch,
    new Commands\Get\PreRelease,
    new Commands\Get\Build,

    // Increment
    new Commands\Increment\Major,
    new Commands\Increment\Minor,
    new Commands\Increment\Patch,
]);

$app->run();
